baseURL = "https://simon020286.github.io/"
languageCode = "it-IT"
title = "T-Dev"
theme = "terminal"

defaultContentLanguage = "it"
disqusShortname = "devdaddy-1"

[params]
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  showMenuItems = 3
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "/images/favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  [params.comments]
      enabled = true

[languages]
  [languages.it]
    title = "T-Dev"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  [languages.it.params.logo]
      logoText = "T-Dev"
      logoHomeLink = "/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3